site_name: Neurobagel Documentation
theme:
  name: material
  palette:
    primary: pink
    accent: light blue
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
repo_url: https://github.com/neurobagel/documentation

# Page Navigation
nav:
  - Welcome: "index.md"
  - Data Models: "datamodels.md"
  - Data dictionaries: "dictionaries.md"
  - mr_proc: 
    - Overview: "mr_proc/overview.md"
    - Installation: "mr_proc/installation.md"
    - Configs: "mr_proc/configs.md"
    - "Code organization": "mr_proc/code_org.md"
    - "Data organization": "mr_proc/data_org.md"

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences