site_name: Neurobagel Documentation
theme:
  name: material
  palette:
    primary: pink
    accent: light blue
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
repo_url: https://github.com/neurobagel/documentation

# Page Navigation
nav:
  - Welcome: "index.md"
  - Data Models: "datamodels.md"

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences